spring.application.name=06_Rest_API_Student_Demo

spring.datasource.url=jdbc:mysql://localhost:3306/student_rest_demo
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true